admin:
    path:     /
    defaults: { _controller: "ProjectBundle:Admin:index" }
admin_movie:
    resource: "@ProjectBundle/Resources/config/routing/admin/movie.yml"
    prefix:   /movie
admin_category:
    resource: "@ProjectBundle/Resources/config/routing/admin/category.yml"
    prefix:   /category
admin_comment:
    resource: "@ProjectBundle/Resources/config/routing/admin/comment.yml"
    prefix:   /comment
admin_orders:
    resource: "@ProjectBundle/Resources/config/routing/admin/orders.yml"
    prefix:   /orders