
comment_new:
    path:     /new
    defaults: { _controller: "ProjectBundle:Comment:new" }

comment_create:
    path:     /create
    defaults: { _controller: "ProjectBundle:Comment:create" }
    methods:  POST
