project_orders_myorders:
    path:     /
    defaults: { _controller: "ProjectBundle:MovieOrder:myOrders" }

project_orders_new:
    path:     /new
    defaults: { _controller: "ProjectBundle:MovieOrder:new" }

project_orders_create:
    path:     /create
    defaults: { _controller: "ProjectBundle:MovieOrder:create" }
    requirements: { _method: post }

project_orders_accepted:
    path:     /{id}/accepted
    defaults: { _controller: "ProjectBundle:MovieOrder:paymentAccepted" }