project_homepage:
    path:     /
    defaults: { _controller: ProjectBundle:Default:index }
project_admin:
    resource: "@ProjectBundle/Resources/config/routing/admin.yml"
    prefix:   /admin
project_movie:
    resource: "@ProjectBundle/Resources/config/routing/movie.yml"
    prefix:   /movie
project_category:
    resource: "@ProjectBundle/Resources/config/routing/category.yml"
    prefix:   /category
project_cart:
    resource: "@ProjectBundle/Resources/config/routing/cart.yml"
    prefix:   /cart
project_comment:
    resource: "@ProjectBundle/Resources/config/routing/comment.yml"
    prefix:   /comment