services:
#    project.example:
#        class: ProjectBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     acme_user.registration.form.type:
        class: ProjectBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: acme_user_registration }