admin_category:
    path:     /
    defaults: { _controller: "ProjectBundle:Category:index" }
admin_category_new:
    path:     /new
    defaults: { _controller: "ProjectBundle:Category:new" }

admin_category_create:
    path:     /create
    defaults: { _controller: "ProjectBundle:Category:create" }
    requirements: { _method: post }

admin_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjectBundle:Category:edit" }

admin_category_update:
    path:     /{id}/update
    defaults: { _controller: "ProjectBundle:Category:update" }
    requirements: { _method: post|put }

admin_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjectBundle:Category:delete" }
    requirements: { _method: post|delete }
