admin_movie:
    path:     /
    defaults: { _controller: "ProjectBundle:Movie:index" }
admin_movie_new:
    path:     /new
    defaults: { _controller: "ProjectBundle:Movie:new" }

admin_movie_create:
    path:     /create
    defaults: { _controller: "ProjectBundle:Movie:create" }
    requirements: { _method: post }

admin_movie_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjectBundle:Movie:edit" }

admin_movie_update:
    path:     /{id}/update
    defaults: { _controller: "ProjectBundle:Movie:update" }
    requirements: { _method: post|put }

admin_movie_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjectBundle:Movie:delete" }
    requirements: { _method: post|delete }